### ISSUE TITLE
Re-Purpose the Freelance Agreements from Summer-2015 repo into General Contributor Agreement

### ISSUE THREAD

**Issue by nelsonic** [dwyl/contributing#1]
See: https://github.com/dwyl/summer-2015/tree/a38e3af064dad8d536bd68dbec58bf84b3d3f95d/freelance-agreements

**Comment by iteles** [comment]
:+1: I've already started on this actually. Totally agree. Linked to https://github.com/dwyl/summer-2015/issues/27#issuecomment-117312900

**Comment by nelsonic** [comment]
@iteles is there anyone you can _delegate_ this work to...? 🤔

**Comment by iteles** [comment]
This was completed in 2017. It can _definitely_ be improved upon and we will open a new issue next time one is needed.
