### ISSUE TITLE
Should the agreement itself be the readme?

### ISSUE THREAD

**Issue by iteles** [dwyl/contributing#2]
Should we have the contributor agreement itself be the readme so that it's the **first thing people see when they open the repo**? 

Or should we have a _thank you_ paragraph and section on how to sign the agreement as the readme with a link to the md file in this repo with the agreement itself (clearly named)?

**Comment by nelsonic** [comment]
@iteles _currently_ the `README.md` starts with "Welcome" and "Thank You" ...
https://github.com/dwyl/contributing/tree/cc3a47b5b4d1157e35f76c0fd5dcea6c0fad20f1
![image](https://user-images.githubusercontent.com/194400/27022775-5f159d28-4f47-11e7-84e1-1c94ab573008.png)

At _present_ we don't have a link to the ***agreement*** _anywhere_. 
Should we add it?

**Comment by iteles** [comment]
`contributing` should now be about our OSS contributions community, we'll keep the agreements in `hq` as a separate thing 👍
