### ISSUE TITLE
For a later date: 'beginner-friendly' label

### ISSUE THREAD

**Issue by iteles** [dwyl/contributing#24]
As a growing open source community, having a 'beginner-friendly' label and clearly noting in this repo what that actually means might be useful to help newer coders feel like they can still contribute. There is often a reluctance to contribute early on in a coder's journey because 'surely it can't be this simple' but having these labels may help combat that. 

This is subjective, but clear guidelines should be enough to ensure this works well. 
https://opensource.com/life/16/1/6-beginner-open-source

Given this subjective nature, I am not inclined to add any other levels of experience as labels.

**Comment by nelsonic** [comment]
@iteles any reason for not discussing this in https://github.com/dwyl/labels ...?

**Comment by iteles** [comment]
I originally had it there and moved it over before hitting send. My thinking was that labels is specifically a label _maker_ app whereas this is an issue around improving contributing. Arguments for both!

**Comment by nelsonic** [comment]
yeah, I would keep _everything_ `labels`-related in the `labels` repo and simply refer people there.

**Comment by iteles** [comment]
Closed in favour of https://github.com/dwyl/labels/issues/36
