### ISSUE TITLE
Creating a new repo - minimum expectations

### ISSUE THREAD

**Issue by iteles** [dwyl/contributing#29]
We have a lot here on how things operate _during_ a project, but as @mk4111 pointed out [here](https://github.com/dwyl/hq/issues/113#issuecomment-254662123), not much about how to _start_ a repo. 

We need to add in the key points around this soon!

+ [x] Initiate the repo _with_ a repo
+ [x] Initiate the repo _with_ a description
+ [x] Sync up the labels using http://label-sync.herokuapp.com
+ [x] Protect `master` branch https://github.com/dwyl/hq/issues/287
+ [x] Remember to add the right people/teams to the repo as collaborators

**Comment by iteles** [comment]
Linked to #27

**Comment by naazy** [comment]
Agreed! I don't think the rules for creating a repo are clear e.g. who can create it/what warrants the creation of a new repo (e.g. does it have to be led by demand etc).

**Comment by mk4111** [comment]
Hi @iteles! Wondering if dwyl/start-here repo would be a good place to mention this? We could maybe have a list of 'common FAQs' that we could check out; we could use it to point users to another repo ( e.g. Q: 'How can I find out more about contributing?' A: 'Go to https://github.com/dwyl/contributing !') and/or answer some general questions ( e.g. Q: 'Where can I ask a generic question?' A: 'Post it as an issue on this repo!' )? 

I know it's a little different, but this was suggested for https://github.com/dwyl/contributing/issues/71#issuecomment-275572776 too, so thought it could maaybe apply for this issue too!

**Comment by iteles** [comment]
@mk4111 Please do go ahead and PR this into start-here if you have the chance - two issues, one stone ;)
