### ISSUE TITLE
Forking repositories into dwyl - why it's not a great idea without very good reason

### ISSUE THREAD

**Issue by iteles** [dwyl/contributing#30]
There is no way to add issues to forked repositories, which means they render our [contributing guidelines](https://github.com/dwyl/contributing) pretty much useless.
<img width="813" alt="screen shot 2016-10-19 at 00 57 03" src="https://cloud.githubusercontent.com/assets/4185328/19500647/106e0954-9597-11e6-8491-dbaf39f88636.png">

We need to add a guideline to this repo on _when_ forking a repo into dwyl _is_ acceptable (I foresee very few situations where this would be the optimal solution) and what the process for that conversation is (open an issue on the dwyl repo that requires a fork of another repo or if there _is_ no dwyl repo, do so on `start-here`).

**Comment by nelsonic** [comment]
Really the _only_ reason to Fork something into dwyl is where _we_ are going to _improve_ on the project and send a patch/PR back up-stream. this does not appear to be the case here...

**Comment by iteles** [comment]
Agreed. I've emailed the person in question.
If it sits for a fortnight with no changes I will delete the fork and it can be re-forked as necessary.

**Comment by nelsonic** [comment]
Is it _hurting_ us to have the fork...?
(_I agree that it's clutter..._)

**Comment by iteles** [comment]
It's clutter. We have _too many_ repos for people to navigate easily so the second they hit one that is 'useless', it affects their interest in the others

**Comment by nelsonic** [comment]
Agreed. Don't know if this issue belongs in "contributing" tho...

**Comment by iteles** [comment]
I would argue that people who fork repos into dwyl rather than into their person GitHub accounts would do it because they feel they are contributing to dwyl in some way (otherwise they would fork to their own accounts).

**Comment by nelsonic** [comment]
Sure, maybe. :+1:
