### ISSUE TITLE
assiging a PR for review before CI passes ... :-(

### ISSUE THREAD

**Issue by nelsonic** [dwyl/contributing#37]
if your pull request does not pass _all_ the tests/linting/coverage threshold,
is it _really_ "***ready***" to be assigned to someone `else` for "review"...?

![check failed](https://cloud.githubusercontent.com/assets/194400/22284176/db2d698a-e2dd-11e6-8799-573226328b6b.png)

**Comment by iteles** [comment]
One of the biggest time-wasters I see :+1:
