### ISSUE TITLE
Why do people create issues without comment/description ...? :-(

### ISSUE THREAD

**Issue by nelsonic** [dwyl/contributing#38]
does _anyone_ think that creating an issue without a comment is enough to _capture_ what is required...?

**Comment by sohilpandya** [comment]
Issues can be created at different stages/times of the day/project. 

For me if they are created first thing in the morning, it'd be understandable to have descriptions attached to them. But what does one do if it's literally the end of the day? 

- If the idea behind creating an issue is to capture an idea/next steps then at least that's been captured and the appropriate additions can be made to it when the person returns to it (they've planted the seed and they know where to begin when they return to the desk - next day/after lunch/after the weekend)

**Comment by nelsonic** [comment]
@sohilpandya you make a _valid_ point, people may be at the end of their day and need to make a "note" of what to do next without going into detail.

I guess I'm just not _used_ to seeing an email with only a subject line and a blank body. 
It _feels_ incomplete/rushed... 

My _concern_ is that it's not an _occasional_ occurrence limited to the circumstances you've described (_which are valid!_) I see F&C people post "_incomplete_" issues way too often and/or start working without putting enough _thought_ into the requirement/user-story before hand.

We need to _improve_ our process and encourage people to finish their day _earlier_ in order to have time to _consider_ what needs to be done next and ensure that the next issue they pick off (_or add to_) the backlog is _well described_ and validated the _day before_ it gets worked on. 
(_there is empirical evidence to support this workflow as it allows your "unconscious" mind to deliberate on the question/challenge ahead of tackling it the following day..._)
