### ISSUE TITLE
Reduce opening paragraph

### ISSUE THREAD

**Issue by katbow** [dwyl/contributing#43]
Much of the information in the first paragraph can be pared down/removed eg. the GPL licensing.

**Comment by iteles** [comment]
Yes PLEASE!

**Comment by nelsonic** [comment]
totes agree. 
https://github.com/dwyl/contributing/blob/9817622d17788d7a49f89a036b702bb0bed0f35f/README.md opening paragraph is _way_ too wordy! thanks for helping us cut it down! 👍
