### ISSUE TITLE
Rewrite steps for section 2 on user stories

### ISSUE THREAD

**Issue by katbow** [dwyl/contributing#48]
[This section](https://github.com/dwyl/contributing#2-create-the-user-story-and-its-technical-tasks) has some steps that cannot be completed by people who do not have access to the repo(s).

For example, they would not be able to add labels for a new issue they are creating. Most of this section can be placed in another section.

**Comment by nelsonic** [comment]
This is _so_ needed!
worth checking out @SimonLab's https://github.com/SimonLab/user-story-checklist ...
_although_ we have a _slightly_ different sequence for our steps. 👍

**Comment by nelsonic** [comment]
I've _reworded_ the _purpose_ of the Contributing Guide _as_ a ***User Story***:

> As a **_distributed_ team**, 
we **_need_** a **contributing guide** with **simple steps** people can **_easily_ follow** 
**so that** we _avoid confusion_ and **keep our _communication consistently crystal clear_**! 

_Thoughts_...?

**Comment by iteles** [comment]
@nelsonic Great idea!
Hadn't even thought of that, feel like we've been burying the lead all this time.
