### ISSUE TITLE
Intro image?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/contributing#52]
I _find_ that having an intro image in a repo makes it more "_people-friendly_" ...
I'd _love_ to have a really _friendly/welcoming_ image ... 
while we search for a _better_ image, what do people think of this:
![welcome-teal](https://cloud.githubusercontent.com/assets/194400/22215755/76cb4dbc-e194-11e6-95ed-7def95e68f14.png)

**Comment by iteles** [comment]
Completely agree :+1:

**Comment by nelsonic** [comment]
![i m new](https://cloud.githubusercontent.com/assets/194400/22240311/8d6bc6e0-e212-11e6-90a3-0fba6f769693.jpg)

**Comment by katbow** [comment]
I like both images for it 👍 . The welcome is nice & friendly and the "I'm new here" should let people easily find a section applicable to them, even if they start by just scanning through ✨ 🎉

**Comment by nelsonic** [comment]
Turned this:
![get sh*t done](http://demos.creative-tim.com/get-shit-done/assets/img/carousel_blue.png)
http://demos.creative-tim.com/get-shit-done/assets/img/carousel_blue.png

into this:
![get-it-done](https://cloud.githubusercontent.com/assets/194400/22265743/44a2ca72-e275-11e6-819d-2c5a1958ea11.png)

😉
