### ISSUE TITLE
Moving the security/privacy concern section further down?

### ISSUE THREAD

**Issue by iteles** [dwyl/contributing#56]
Having [this security/privacy concern section](https://github.com/dwyl/contributing#got-a-securityprivacy-concern-or-question) at the top means that there is no section of the step-by-step process which is the content of this repo that shows up 'above the fold' once you've scrolled down to the readme on a desktop:
<img width="988" alt="dwyl-contributing-repo-nothing-above-the-fold" src="https://cloud.githubusercontent.com/assets/4185328/22264813/42dfae20-e271-11e6-9423-21fbb79b1891.png">

We might want to give people a glimpse of what they came here for *quickly* so they don't get distracted/start scrolling and just scroll past everything without reading it.

Thoughts welcome as this is just a personal impression!

**Comment by nelsonic** [comment]
@iteles I _debated_ ***where*** to put the Security clause...
I think pushing it down in the Readme _de-emphasises_ it...
But equally 99.9% of issues/contributions will _not_ be security-related.
so _forcing_ people to read the paragraph when they _don't_ have a Security-related question/issue,
is _probably_ just _annoying_ people. right...?

**Comment by iteles** [comment]
That would be my view based on experience: if people see content that's not relevant to them, they'll immediately start skimming with a different mindset.

**Comment by nelsonic** [comment]
Agreed. moving it. 👍
