### ISSUE TITLE
Introductory sentence on use of issues?

### ISSUE THREAD

**Issue by iteles** [dwyl/contributing#57]
The first step in the process is to search through the backlog for existing issues.

<img width="844" alt="screen shot 2017-01-24 at 20 18 15" src="https://cloud.githubusercontent.com/assets/4185328/22265048/4998e01e-e272-11e6-975c-351eb9ef2a33.png">

But if I don't know that the backlog is managed through issues and I will be expected to raise one before starting work, will this make sense to me?

My suggestion here would be something like this to provide context:
> At dwyl we use _issues_ to log our user stories (and technical tasks) to ensure we have a [single version of the truth](https://github.com/dwyl/github-reference#why).        

My expectation is that the link in this section explains enough if people need it.

https://github.com/dwyl/contributing/commit/d7c9580fedce988e029a8587a8f7bdd39e77f3ca#diff-04c6e90faac2675aa89e2176d2eec7d8R43

**Comment by nelsonic** [comment]
Good thinking [_Brain!_](https://www.youtube.com/watch?v=v-xrnIXQ3iQ) 🐭
