### ISSUE TITLE
validating an issue/story before working on it...

### ISSUE THREAD

**Issue by nelsonic** [dwyl/contributing#59]
How do we _communicate_ the _need_ to _validate_ a user story or issue _before_ work can commence?
Some good diagrams here: http://gemklip.com/contribute/

I turned this:
![share-etd-1](https://cloud.githubusercontent.com/assets/194400/22266759/1bbd0f4c-e279-11e6-8e06-5a0ecc1e7c47.jpg)
from: http://gemklip.com/wp-content/uploads/2016/06/Share-etd-1.jpg

into:
![validate-idea](https://cloud.githubusercontent.com/assets/194400/22266650/c22bcfd6-e278-11e6-80e3-d587cbaa68e9.png)

# _Thoughts_...?

Alternative:
![did you validate it](https://www.apptentive.com/wp-content/uploads/2015/06/validate.jpg)
from: https://www.apptentive.com/wp-content/uploads/2015/06/validate.jpg

**Comment by nelsonic** [comment]
@iteles if you _liked_ that then you'll _love_ this:
![validate-idea](https://cloud.githubusercontent.com/assets/194400/22267264/17ebd78e-e27b-11e6-8328-e9665b53dde0.png)

I _clarified_ in the diagram ***Who***...

**Comment by nelsonic** [comment]
@iteles Are the _numbers_ too much?
![validate-idea](https://cloud.githubusercontent.com/assets/194400/22267758/f14f04d2-e27c-11e6-9b81-dd8673372a4b.png)

**Comment by nelsonic** [comment]
Going with:
![validate-idea](https://cloud.githubusercontent.com/assets/194400/22268041/e2f45df0-e27d-11e6-9c86-41e898b70701.png)
But _happy_ for someone `else` to do a better job of this...

**Comment by iteles** [comment]
Much better without the numbers as discussed 👍

**Comment by nelsonic** [comment]
cool. thanks @iteles 👍

**Comment by nelsonic** [comment]
_Spot_ the _difference_ (_clarification_...):
![validate-idea](https://cloud.githubusercontent.com/assets/194400/22287004/1cde1ebe-e2e9-11e6-9c00-8a0312d0ba6d.png)

**Comment by nelsonic** [comment]
Expanded the wording a bit and _underlined_ the key words in the steps:
![validate-idea](https://cloud.githubusercontent.com/assets/194400/22287688/a929a9ae-e2eb-11e6-8d16-f2ebbebea080.png)

**Comment by Cleop** [comment]
I like it @nelsonic 🎊 , Is this ready to close now? And if it is, is #58 ready to be closed too?

**Comment by nelsonic** [comment]
@Cleop thanks for reminding us to `close` the issue. 👍
