### ISSUE TITLE
PR Review Process is Unclear ... :-(

### ISSUE THREAD

**Issue by nelsonic** [dwyl/contributing#64]
as a `team member` (_developer_) want to _ship_ my work to end-users ASAP
I `need` to `know` what the `QA/review process` is 
so that I `know when` I can expect my work on this `PR/story` is considered `done`.
(_so that I'm **not waiting** to **start work** on my **next story**..._)

Pain felt by team member:
![unclear-on-pr-review-process](https://cloud.githubusercontent.com/assets/194400/22290447/afcb5214-e2f8-11e6-94a8-96dc658df993.png)

Let's _fix_ this ***now***!

relates to: https://github.com/dwyl/contributing/issues/32#issuecomment-271089111

**Comment by ghost** [comment]
I agree. this needs to be clarified. especially for beginners. 👍

**Comment by nelsonic** [comment]
Should we _consider_ dissalowing merging one's _own_ Pull Request on GitHub?
http://stackoverflow.com/questions/23858386/disallow-merging-your-own-pull-request-on-github
***Or*** is there a _situation_ where being _able_ to merge your _own_ PR is _useful_?

**Comment by iteles** [comment]
Nope. Let's disallow merging of one's PR until we find the exception. In 2 years we've never yet had to do this.

**Comment by nelsonic** [comment]
Use the GitHub Review process:
![review-changes-submit](https://cloud.githubusercontent.com/assets/194400/22298017/f45fa20e-e316-11e6-8fd6-d9825f5ce682.png)

**Comment by nelsonic** [comment]
![multiple-reviewers](https://cloud.githubusercontent.com/assets/194400/22298681/49d12d82-e319-11e6-829e-c0c146b80185.png)

It's not _uncommon_ to see a PR with _multiple_ review approvals. 
this is our "_peer review_" process _working_ to share knowledge 
& code understanding among the team. ✅

**Comment by iteles** [comment]
@nelsonic Can this now be closed?

**Comment by nelsonic** [comment]
@iteles yes! someone else can open a more _specific_ question if/when they need to. 👍
