### ISSUE TITLE
Add 'question' to list of things issues can be opened for

### ISSUE THREAD

**Issue by mk4111** [dwyl/contributing#72]
As someone who often feels unsure and wants to ask lots of questions before diving into something, I think adding 'question' to [the list of things for which issues are for](https://github.com/dwyl/contributing/blame/master/README.md#L231) would be reassuring...

Tiny tiny suggestion but I think it could be helpful for humans like meee :sparkles:

**Comment by nelsonic** [comment]
@mk4111 _agree 100%_.
the word `"question"` is mentioned a couple of times in the Readme e.g: https://github.com/dwyl/contributing/blame/4f38e20b95eb6d3a950e6f8f9f44bbd977ae87d8/README.md#L452
and:
https://github.com/dwyl/contributing/blame/4f38e20b95eb6d3a950e6f8f9f44bbd977ae87d8/README.md#L154
and:
https://github.com/dwyl/contributing/blame/4f38e20b95eb6d3a950e6f8f9f44bbd977ae87d8/README.md#L240

But ***agree*** that we should _really_ be _explicit_ 
that raising an issue _can_ be ***just*** to ask a clarifying question. 👍 
please help us _improve_ the Readme to this effect. thanks! ❤️  ✅

**Comment by mk4111** [comment]
@nelsonic, about to make a PR; please let me know your honest opinions on whether you think it makes the text too noisy or if it's a positive change!! Thank you!

**Comment by mk4111** [comment]
Resolved with #93
