### ISSUE TITLE
How do you know who to assign your PR to?

### ISSUE THREAD

**Issue by mk4111** [dwyl/contributing#73]
If somebody on the other side of the world wants to contribute to dwyl repos, but knows nobody _but_ the validator of their issue, should this person be assigned the PR to the issue raised when it is ready for review?

I think it could be handy to suggest this somewhere in the repo - maybe [here](https://github.com/dwyl/contributing/blame/master/README.md#L373)?

**Comment by nelsonic** [comment]
@mk4111 _superb_ question! 👍 

There's a _note_ for this lower down:
https://github.com/dwyl/contributing/blame/4f38e20b95eb6d3a950e6f8f9f44bbd977ae87d8/README.md#L621-L623

But it still isn't _specific_ that you can _assign_ it to:
> the **Project/Team Lead or "QA"** (_where applicable_) 
***or*** in the case of an open source module, our "_rule-of-thumb_" is: look at the list of contributors 
and ***assign*** your PR to the **person** who has made the **_most_ contributions**.
if you are _unable_ to assign your PR, simply _mention_ the person's by name in your PR description to notify them that your PR is "_ready for review_".

The _general_ guideline that your PR should be _assigned_ to "***someone else***" was _simply_ to _remind_ people not to be _tempted_ to merge their own PRs...
I _agree_ that we should be _specific_ on who you _can_/_should_ assign it ***to***... 👍 

Please PR a clarification.
_Specifically_ add a "_Question_" to the "FAQ" section.
thanks! (_if unclear please let us know!_) 👍 
relates to: #71

**Comment by mk4111** [comment]
@nelsonic, that makes sense! I'll add a Question to `FAQ` right away! Thank you for the clarification! Yippeeeee

**Comment by mk4111** [comment]
Closing this as has been resolved by #92
