### ISSUE TITLE
Spelling and Grammar

### ISSUE THREAD

**Issue by ghost** [dwyl/contributing#77]
Number of errors in the text

e.g.
https://github.com/dwyl/contributing/blame/master/README.md#L149
Should say `been` rather than `ben`

Requesting the need for a PR with corrections throughout text after completing a spelling and grammar check.

Links to #66

**Comment by iteles** [comment]
👍 Thanks @markwilliamfirth, please PR in the changes!

**Comment by samhstn** [comment]
Can this be closed?

**Comment by Jbarget** [comment]
found another spelling mistake, under "General Notes" -> "Inspired By.." -> "addapted" should be "adapted". shall i commit against this issue or another one?

https://github.com/dwyl/contributing/blame/master/README.md#L657

**Comment by ghost** [comment]
@Jbarget go ahead with this one - we can make it the general spelling and grammar issue :)

**Comment by Jbarget** [comment]
dont have write access

**Comment by nelsonic** [comment]
@Jbarget tried to add you:
![image](https://cloud.githubusercontent.com/assets/194400/23727499/39cfb14e-0450-11e7-9fb0-99660199d61c.png)

Added a team instead ... please confirm you have write access by applying assigning yourself to the issue.

**Comment by iteles** [comment]
Completed for now :+1:
