### ISSUE TITLE
Quote at Start of Guide Taking up Space

### ISSUE THREAD

**Issue by ghost** [dwyl/contributing#82]
Is a quote desirable / necessary?

If the intention is to slim this down as much as possible, it might be worth considering its removal.

**Comment by nelsonic** [comment]
Hmm... I'm quite "_emotionally attached_" to the quote ... 💭 
I `feel` that it sets the "_tone_" for how we _think_ about contributions to the projects/org/mission ... ❤️ 
it's not _just_ [**hurry up and give us your issues, ideas and code**](https://youtu.be/N_dUmDBfp6k?t=1m21s) ... ⏳  ✅ 

This is _exactly_ the kind of thing that we need to "A/B Test" ... but the question is ***how***? 🤔

**Comment by iteles** [comment]
There were no further validations for this issue and for now I think it sets a good tone.
Let's come back to this when we have a more full content review #83
