### ISSUE TITLE
Process - Review or Assign?

### ISSUE THREAD

**Issue by ghost** [dwyl/contributing#86]
For the following line:

https://github.com/dwyl/contributing/blob/master/README.md#3-pr-ettiquete

It's not clear if one should use the Github Assign feature or the Github Reviewer feature

What is the correct process to follow? I assume using the review feature is enough without also additionally Assigning the same reviewer

@nelsonic ?

**Comment by nelsonic** [comment]
@markwilliamfirth ***yes***, the Review feature is a _recent_ development. 
Assigning a PR or Requesting a Review ***can*** be used interchangeably. 
However I would say that while we can Request Review from _multiple_ people we should really only _assign_ it to ***one*** person (_at a time_) so it's clear who's _responsibility_ the work is.
If a person is Requesting Review do they _need_ to ***also*** assign the PR to the same person?
No, that feels like overkill to me. (_an extra step without much value_) 

The only thing to **note** is: if we use the Request Review to ask a specific person for review,
if the person asks for "_modifications_" to be made to the PR _before_ it can be merged, 
it will still _look_ like the PR is being reviewed as opposed to being the "_responsibility_" of the person who _prepared_ the PR ... for example:
![pull-request-reviewer-assigned](https://cloud.githubusercontent.com/assets/194400/22506324/bf78f750-e877-11e6-8d53-9fab109935b8.png)
I have reviewed a PR for a project but requested changes, I cannot "_remove_" myself from the reviewers list but I can ***assign*** it ***back*** to the person who created the PR ...
The workflow does work, but it requires some _explaining_...

**Comment by mk4111** [comment]
...so @nelsonic does that mean we should try and 'Assign' over 'Review'...?

**Comment by iteles** [comment]
@mk4111 Until github fixes its interface, that's the preference 👍

**Comment by iteles** [comment]
Closing as for now the readme read 'assign your PR'
<img width="614" alt="screen shot 2017-07-30 at 18 49 48" src="https://user-images.githubusercontent.com/4185328/28755669-e990d932-7557-11e7-8122-b8eb87c17960.png">

Will reopen if required
