### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by ghost** [dwyl/contributing#90]
Test Description

**Comment by nelsonic** [comment]
DWYLBOT: if you (_or anyone else_) have time, please fix this.

**Comment by iteles** [comment]
Suggest:

> DWYLBOT: Thanks for raising this issue! If you (_or anyone else_) have time, please submit a PR for this [once it has been validated](https://github.com/dwyl/contributing).

**Comment by nelsonic** [comment]
@iteles that's _much_ better copy. 😍

**Comment by iteles** [comment]
@markwilliamfirth What's happening with this?

**Comment by ghost** [comment]
This was just a test issue for writing the guide - can be closed
